name: orgro
description: An Org Mode file viewer
version: 1.28.3+66
homepage: https://orgro.org

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.4"

dependencies:
  cached_network_image: ^3.0.0
  dynamic_fonts: ^2.1.0-eager.0
  # dynamic_fonts:
  #   path: ../dynamic-fonts-flutter
  # file_picker_writable: ^2.0.0
  file_picker_writable:
  #   path: ../file_picker_writable
    git:
      url: https://github.com/amake/file_picker_writable.git
      ref: directory-picker
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_cache_manager: ^3.3.0
  flutter_charset_detector: ^1.0.0
  # flutter_charset_detector:
  #   path: ../flutter_charset_detector
  google_fonts: ^4.0.1
  http: ^0.13.0
  intl: ^0.18.0
  org_flutter: ^3.1.0-pre.1
  # org_flutter:
    # path: ../org_flutter
  path_provider: ^2.0.9
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/manual/
    - assets/fonts/
